server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          maxAge: 360000 # 这次跨域检查的有效期
      routes:
        - id: user-service  # 路由标识，必须唯一
          uri: lb://userserver # 路由的目标地址
          predicates:  # 路由断言，判断请求是否符合规则
            - Path=/user/**  # 路径断言，判断路径是否以user开头
          filters:
            - AddRequestHeader=Truth,itcast is freaking awesome!